services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: estatemind_postgres
    environment:
      POSTGRES_DB: estatemind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: capTEEMO500
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
