# Generated by Django 6.0.2 on 2026-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBehaviorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.CharField(max_length=100)),
                ("behavior_type", models.CharField(max_length=30)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("referrer", models.CharField(blank=True, max_length=200, null=True)),
                ("search_query", models.TextField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_behavior_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("listing_id", models.CharField(blank=True, max_length=100, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserRecommendationsCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listing_id", models.CharField(max_length=100)),
                ("recommendation_score", models.FloatField(default=0.5)),
                (
                    "recommendation_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_recommendations_cache",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("search_query", models.TextField()),
                ("filters", models.JSONField(default=dict)),
                ("results_count", models.IntegerField(default=0)),
                (
                    "clicked_listing_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_search_history",
                "managed": False,
            },
        ),
    ]
