# Generated by Django 6.0.2 on 2026-04-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_governorate_delegation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentmetrics",
            options={"ordering": ["-run_started_at"]},
        ),
    ]
