# Generated by Django 6.0.2 on 2026-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_agentmetrics_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmetrics",
            name="consecutive_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="disabled_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="errors",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="fetched",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="inserted",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="run_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="run_started_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="source_name",
            field=models.CharField(
                db_index=True, default="temporary_source", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="strategy",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="unchanged",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agentmetrics",
            name="updated",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="agentmetrics",
            index=models.Index(
                fields=["source_name", "run_started_at"],
                name="services_a_source__45aec1_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="agentmetrics",
            table=None,
        ),
    ]
