# Generated by Django 6.0.4 on 2026-05-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_agentmetrics_consecutive_failures_and_more"),
    ]

    operations = []
