# Generated by Django 6.0.2 on 2026-04-11 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("run_started_at", models.DateTimeField(null=True)),
                ("run_finished_at", models.DateTimeField(null=True)),
                ("source_name", models.TextField(null=True)),
                ("strategy", models.TextField(null=True)),
                ("fetched", models.IntegerField(null=True)),
                ("inserted", models.IntegerField(null=True)),
                ("updated", models.IntegerField(null=True)),
                ("unchanged", models.IntegerField(null=True)),
                ("errors", models.IntegerField(null=True)),
                ("consecutive_failures", models.IntegerField(null=True)),
                ("disabled_until", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "agent_metrics",
                "ordering": ["-run_started_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_name", models.TextField()),
                ("title", models.TextField()),
                ("description", models.TextField(null=True)),
                ("url", models.TextField(null=True)),
                ("price", models.FloatField(null=True)),
                ("currency", models.TextField(default="TND", null=True)),
                ("scraped_at", models.DateTimeField(null=True)),
                ("last_updated", models.DateTimeField(null=True)),
                ("region", models.TextField(null=True)),
                ("city", models.TextField(null=True)),
                ("municipalite", models.TextField(null=True)),
                ("zone", models.TextField(null=True)),
                ("surface", models.FloatField(null=True)),
                ("rooms", models.IntegerField(null=True)),
                ("transaction_type", models.TextField(null=True)),
                ("type", models.TextField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("price_per_m2", models.FloatField(null=True)),
                ("fraud_flag", models.BooleanField(default=False, null=True)),
                ("fraud_score", models.FloatField(null=True)),
                ("fraud_reason", models.TextField(null=True)),
                ("reliability_score", models.FloatField(null=True)),
                ("reliability_level", models.TextField(null=True)),
                ("is_outlier", models.BooleanField(default=False, null=True)),
                ("outlier_flags", models.JSONField(default=list, null=True)),
                ("suspected_duplicate", models.BooleanField(default=False, null=True)),
                ("features", models.JSONField(default=list, null=True)),
                ("images", models.JSONField(default=list, null=True)),
                ("images_count", models.IntegerField(null=True)),
                ("change_type", models.TextField(null=True)),
                ("has_price_history", models.BooleanField(default=False, null=True)),
                ("price_delta", models.FloatField(null=True)),
                ("price_delta_pct", models.FloatField(null=True)),
                ("nlp_enriched", models.BooleanField(default=False, null=True)),
                ("normalized", models.BooleanField(default=False, null=True)),
                ("should_drop", models.BooleanField(default=False, null=True)),
            ],
            options={
                "db_table": "listings",
                "ordering": ["-scraped_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("particular", "Particulier"),
                            ("agency", "Agence"),
                            ("analyst", "Analyste"),
                            ("admin", "Administrateur"),
                        ],
                        default="particular",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("agency_name", models.CharField(blank=True, max_length=200)),
                ("matricule_fiscale", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
